import { homedir } from "node:os";
import path from "node:path";

export const SETUP_PRESETS = Object.freeze({
  personal: Object.freeze({
    label: "个人安全（推荐）",
    sandboxMode: "workspace-write",
    operatorSandboxMode: "workspace-write",
    networkAccess: false,
    webSearchMode: "disabled",
  }),
  team: Object.freeze({
    label: "团队安全",
    sandboxMode: "workspace-write",
    operatorSandboxMode: "workspace-write",
    networkAccess: false,
    webSearchMode: "disabled",
  }),
  power: Object.freeze({
    label: "高级模式",
    sandboxMode: "danger-full-access",
    operatorSandboxMode: "workspace-write",
    networkAccess: false,
    webSearchMode: "disabled",
  }),
});

export function normalizeInstanceId(value = "default") {
  const normalized = value
    .trim()
    .toLocaleLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
  if (!normalized) throw new Error("实例名称至少需要包含一个字母或数字。");
  return normalized;
}

export function splitCsv(value = "") {
  return [...new Set(value.split(",").map((item) => item.trim()).filter(Boolean))];
}

export function validateOpenIds(value, label = "open_id") {
  const ids = Array.isArray(value) ? value : splitCsv(value);
  if (ids.length === 0) throw new Error(`${label} 不能为空。`);
  for (const id of ids) {
    if (!/^ou_[A-Za-z0-9_-]+$/.test(id)) {
      throw new Error(`${label}“${id}”格式不正确，应以 ou_ 开头。`);
    }
  }
  return ids;
}

export function validateChatIds(value, label = "chat_id") {
  const ids = Array.isArray(value) ? value : splitCsv(value);
  for (const id of ids) {
    if (!/^oc_[A-Za-z0-9_-]+$/.test(id)) {
      throw new Error(`${label}“${id}”格式不正确，应以 oc_ 开头。`);
    }
  }
  return ids;
}

export function defaultSetupPaths(instanceId = "default", home = homedir()) {
  const instance = normalizeInstanceId(instanceId);
  return {
    instance,
    configDir: path.join(home, ".config", "feishu-codex-bridge"),
    configFile: path.join(home, ".config", "feishu-codex-bridge", `${instance}.env`),
    dataDir: path.join(home, ".local", "share", "feishu-codex-bridge", instance),
  };
}

export function buildEnvFile(options) {
  const preset = SETUP_PRESETS[options.preset];
  if (!preset) throw new Error(`未知权限预设：${options.preset}`);
  const operators = validateOpenIds(options.operatorIds, "操作者 open_id");
  const admins = validateOpenIds(options.adminIds?.length ? options.adminIds : operators, "管理员 open_id");
  const viewers = splitCsv((options.viewerIds ?? []).join?.(",") ?? options.viewerIds ?? "");
  if (viewers.length > 0) validateOpenIds(viewers, "只读成员 open_id");
  const chats = splitCsv((options.chatIds ?? []).join?.(",") ?? options.chatIds ?? "");
  validateChatIds(chats, "群聊 chat_id");
  const workdir = path.resolve(options.workdir);
  const roots = splitCsv((options.projectRoots ?? []).join?.(",") ?? options.projectRoots ?? "")
    .map((root) => path.resolve(root));
  const lines = [
    "# Generated by feishu-codex-bridge init. Keep this file private.",
    "BRIDGE_CONFIG_VERSION=1",
    `BRIDGE_INSTANCE_ID=${envValue(options.instanceId)}`,
    `BRIDGE_DATA_DIR=${envValue(path.resolve(options.dataDir))}`,
    `ALLOWED_FEISHU_OPEN_IDS=${envValue(operators.join(","))}`,
    `FEISHU_ADMIN_OPEN_IDS=${envValue(admins.join(","))}`,
    `FEISHU_VIEWER_OPEN_IDS=${envValue(viewers.join(","))}`,
    `FEISHU_MEMBER_LABELS_JSON=${envValue(options.memberLabelsJson ?? "")}`,
    `ALLOWED_FEISHU_CHAT_IDS=${envValue(chats.join(","))}`,
    "FEISHU_GROUP_SESSION_SCOPE=member",
    `CODEX_WORKDIR=${envValue(workdir)}`,
    "CODEX_SYNC_SAVED_PROJECTS=true",
    `CODEX_PROJECT_ROOTS=${envValue(roots.join(","))}`,
    `CODEX_SANDBOX_MODE=${preset.sandboxMode}`,
    `CODEX_OPERATOR_SANDBOX_MODE=${preset.operatorSandboxMode}`,
    `CODEX_NETWORK_ACCESS=${preset.networkAccess}`,
    `CODEX_WEB_SEARCH_MODE=${preset.webSearchMode}`,
    "CODEX_MULTI_AGENT_ENABLED=false",
    "FEISHU_AUTO_ONBOARDING=true",
    "FEISHU_COMPLETION_NOTIFICATIONS=false",
    "LOG_MESSAGE_CONTENT=false",
    "",
  ];
  return lines.join("\n");
}

export function envValue(value) {
  const text = String(value ?? "");
  if (text === "") return "";
  if (!/[\s#'"\\]/.test(text)) return text;
  return `"${text.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}
